### ISSUE TITLE
ESI /characters/0/ call no longer works, causes RunTimeException

### ISSUE THREAD

**Issue by cdanek** [Bertral/EANM#6]
https://esi.evetech.net/latest/characters/0/?datasource=tranquility now requires an ID of 1+

> java -jar EANM.jar

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://esi.evetech.net/latest/characters/0/?datasource=tranquility
        at SettingFile.getInfos(SettingFile.java:64)
        at SettingFile.getCharName(SettingFile.java:50)
        at SettingFile.toString(SettingFile.java:39)
        at EANM.initUI(EANM.java:47)
        at EANM.<init>(EANM.java:130)
        at EANM.main(EANM.java:19)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://esi.evetech.net/latest/characters/0/?datasource=tranquility

**Comment by cdanek** [comment]
My apologies, didn't have latest version. Closing.
